SalsaEvent/src/Lmi/EventBundle/Entity/Event.php
<?php

namespace Lmi\EventBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\Criteria;

/**
 * Event
 *
 * @ORM\Table()
 * @ORM\Entity(repositoryClass="Lmi\EventBundle\Entity\EventRepository")
 */
class Event extends AbstractEntity
{
    /**
     * @var string
     *
     * @ORM\Column(name="identification", type="string", length=255, nullable=true)
     */
    private $identification;
    
    /**
     * @ORM\OneToMany(targetEntity="Lmi\EventBundle\Entity\Soiree", mappedBy="event", cascade={"persist", "remove", "merge"})
     */
    private $soirees; 
    
    /**
     * @ORM\OneToMany(targetEntity="Lmi\EventBundle\Entity\Stage", mappedBy="event", cascade={"persist", "remove", "merge"})
     */
    private $stages;
    
    /**
     * @ORM\ManyToMany(targetEntity="Lmi\EventBundle\Entity\DanceSchool", cascade={"persist", "remove"})
     */
    private $organisateurs;
    
    /**
     * @ORM\OneToMany(targetEntity="Lmi\EventBundle\Entity\CarPooling", mappedBy="event", cascade={"persist"})
     */
    private $carpoolings;
    
    /**
     * @ORM\ManyToMany(targetEntity="Lmi\EventBundle\Entity\Accommodation", mappedBy="events", cascade={"persist", "remove"})
     * @ORM\JoinTable(name="event_accommodation")
     */
    private $hebergements;
    
    /**
     * @ORM\ManyToOne(targetEntity="Lmi\EventBundle\Entity\Adresse", cascade={"persist", "remove"})
     */
    private $adresse;
    
    /**
     * @ORM\OneToOne(targetEntity="Lmi\EventBundle\Entity\Image", cascade={"persist", "remove"})
     */
    private $flyer;
    
    //private $concerts
    //private $commerces
    
    /**
     * Constructor
     */
    public function __construct()
    {
    	parent::__construct();
        $this->soirees = new \Doctrine\Common\Collections\ArrayCollection();
        $this->stages = new \Doctrine\Common\Collections\ArrayCollection();
        $this->organisateurs = new \Doctrine\Common\Collections\ArrayCollection();
        $this->carpoolings = new \Doctrine\Common\Collections\ArrayCollection();
    }
    
    /**
     * Add soirees
     *
     * @param \Lmi\EventBundle\Entity\Soiree $soiree
     * @return Event
     */
    public function addSoiree(\Lmi\EventBundle\Entity\Soiree $soiree)
    {
        $this->soirees[] = $soiree;
        $soiree->setEvent($this);
    
        return $this;
    }
    
    /**
     * Remove soirees
     *
     * @param \Lmi\EventBundle\Entity\Soiree $soiree
     */
    public function removeSoiree(\Lmi\EventBundle\Entity\Soiree $soiree)
    {
        $this->soirees->removeElement($soiree);
    }

    /**
     * Get soirees
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getSoirees()
    {
        return $this->soirees;
    }

    /**
     * Add stages
     *
     * @param \Lmi\EventBundle\Entity\Stage $stage
     * @return Event
     */
    public function addStage(\Lmi\EventBundle\Entity\Stage $stage)
    {
        $this->stages[] = $stage;
        $stage->setEvent($this);
    
        return $this;
    }

    /**
     * Remove stage
     *
     * @param \Lmi\EventBundle\Entity\Stage $stage
     */
    public function removeStage(\Lmi\EventBundle\Entity\Stage $stage)
    {
        $this->stages->removeElement($stage);
    }

    /**
     * Get stages
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getStages()
    {
        return $this->stages;
    }

    /**
     * Set identification
     *
     * @param string $identification
     * @return Event
     */
    public function setIdentification($identification)
    {
        $this->identification = $identification;
    
        return $this;
    }

    /**
     * Get identification
     *
     * @return string 
     */
    public function getIdentification()
    {
        return $this->identification;
    }

    /**
     * Set adresse
     *
     * @param \Lmi\EventBundle\Entity\Adresse $adresse
     * @return Event
     */
    public function setAdresse(\Lmi\EventBundle\Entity\Adresse $adresse = null)
    {
        $this->adresse = $adresse;
    
        return $this;
    }

    /**
     * Get adresse
     *
     * @return \Lmi\EventBundle\Entity\Adresse 
     */
    public function getAdresse()
    {
        return $this->adresse;
    }

    /**
     * Set flyer
     *
     * @param \Lmi\EventBundle\Entity\Image $flyer
     * @return Event
     */
    public function setFlyer(\Lmi\EventBundle\Entity\Image $flyer = null)
    {
        $this->flyer = $flyer;
    
        return $this;
    }

    /**
     * Get flyer
     *
     * @return \Lmi\EventBundle\Entity\Image 
     */
    public function getFlyer()
    {
        return $this->flyer;
    }

    /**
     * Get desciptif
     *
     * @return string
     */
    public function getDescriptif()
    {
    	return 'descriptif';
    }
    

    /**
     * Add organisateurs
     *
     * @param \Lmi\EventBundle\Entity\DanceSchool $organisateur
     * @return Soiree
     */
    public function addOrganisateur(\Lmi\EventBundle\Entity\DanceSchool $organisateur)
    {
    	$this->organisateurs[] = $organisateur;
    	
    	return $this;
    }
    
    /**
     * Remove organisateur
     *
     * @param \Lmi\EventBundle\Entity\DanceSchool $organisateur
     */
    public function removeOrganisateur(\Lmi\EventBundle\Entity\DanceSchool $organisateur)
    {
    	$this->organisateurs->removeElement($organisateur);
    }
    
    /**
     * Get organisateurs
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getOrganisateurs()
    {
    	return $this->organisateurs;
    }
    
    /**
     * Add carpooling
     *
     * @param \Lmi\EventBundle\Entity\CarPooling $carpooling
     * @return Event
     */
    public function addCarpooling(\Lmi\EventBundle\Entity\CarPooling $carpooling)
    {
        $this->carpoolings[] = $carpooling;
        $carpooling->setEvent($this);
    
        return $this;
    }

    /**
     * Remove carpooling
     *
     * @param \Lmi\EventBundle\Entity\CarPooling $carpooling
     */
    public function removeCarpooling(\Lmi\EventBundle\Entity\CarPooling $carpooling)
    {
        $this->carpoolings->removeElement($carpooling);
    }

    /**
     * Get carpoolings
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getCarpoolings()
    {
        return $this->carpoolings;
    }
    
    /**
     * Get carpoolings
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getAvailableCarpoolings()
    {
    	$criteria = Criteria::create();
    	$criteria->where(Criteria::expr()->gte('dateDepart', new \DateTime()));
    	
    	return $this->carpoolings->matching($criteria);
    }

    /**
     * Add hebergement
     *
     * @param \Lmi\EventBundle\Entity\Accommodation $hebergement
     * @return Event
     */
    public function addHebergement(\Lmi\EventBundle\Entity\Accommodation $hebergement)
    {
        $this->hebergements[] = $hebergement;
        $hebergement->addEvent($this);
    
        return $this;
    }

    /**
     * Remove hebergements
     *
     * @param \Lmi\EventBundle\Entity\Accommodation $hebergements
     */
    public function removeHebergement(\Lmi\EventBundle\Entity\Accommodation $hebergements)
    {
        $this->hebergements->removeElement($hebergements);
    }

    /**
     * Get hebergements
     *
     * @return \Doctrine\Common\Collections\Collection 
     */
    public function getHebergements()
    {
        return $this->hebergements;
    }
    
    /**
     * Get hebergements
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getAvailableHebergements()
    {
    	$criteria = Criteria::create();
    	$criteria->where(Criteria::expr()->gte('periode.dateFin', new \DateTime()));
    	 
    	return $this->hebergements->matching($criteria);
    }
    
    /**
     * Get all types of music for the event
     */
    public function  getAmbiances() 
    {
    	$ambiances = array();
    	$arrSoirees = $this->soirees->toArray();
    	
    	foreach ($arrSoirees as $soiree){
    		$ambiances = array_merge($ambiances, $soiree->getAmbiances());
    	}
    	return $ambiances;
    }
    
    /**
     * Get the main organizer
     */
    public function  getMainOrganizer()
    {
    	$arrOrganizers = $this->organisateurs->toArray();
    	
    	if(count($arrOrganizers) !== 0) {
    		return $arrOrganizers[0]->getNom();
    	}
    	
    	return null;
    }
}

SalsaEvent/src/Lmi/EventBundle/Form/EventType.php
<?php

namespace Lmi\EventBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Lmi\EventBundle\Constants\Constants;

class EventType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom', 'text', array('label' => 'form.field.name'))
			->add('description', new TexteType(), array('required' => false, 'label' => 'form.field.description', 'attr' => array('class' => 'master')))
			->add('periode', new PeriodeType(Constants::CLASS_EVENT), array('required' => false, 'label' => ' '))
            ->add('adresse',  new AdresseType(), array('label' => 'form.field.address', 'attr' => array('class' => 'master')))
            ->add('link', 'text', array('required' => false, 'label' => 'form.field.link', 'attr' => array('class' => 'lien')))
            ->add('tel', 'text', array('required' => false, 'label' => 'form.field.phone.number'))
            ->add('logo', new ImageType(false), array('required' => false, 'label' => 'form.field.logo', 'attr' => array('class' => 'subContent')))
			->add(Constants::FORM_INPUT_PUBLICATION, 'checkbox', array('required' => false, 'label' => 'form.field.publication', 'isPublishOption' => 'yes'))
        ;
    }

    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Lmi\EventBundle\Entity\Event'
        ));
    }

    public function getName()
    {
        return 'lmi_eventbundle_eventtype';
    }
}

SalsaEvent/src/Lmi/EventBundle/Controller/EventController.php
<?php
namespace Lmi\EventBundle\Controller;
 
use JMS\SecurityExtraBundle\Annotation\Secure;
use Lmi\CoreBundle\Constants\Constants;
use Lmi\CoreBundle\Entity\Event;
use Lmi\EventBundle\Form\SearchEventType;
use Lmi\CoreBundle\Outils\DateOutils;
use Lmi\CoreBundle\Constants\ConstViews;
use Lmi\CoreBundle\Constants\ConstServices;
use Lmi\CoreBundle\Controller\AbstractController;
use Lmi\CoreBundle\Constants\ConstClasses;
use Lmi\CoreBundle\Constants\ConstParamAttributs;
 
class EventController extends AbstractController
{
	/** Year format. */
	const YEAR_FORMAT = 'Y';
	
	/** Nb events started. */
	const NB_EVENTS_STARTED = 'nbStartedEvent';
	
	/**
	 * Index
	 */
	public function indexAction($page)
	{
		// check page id
		$this->checkPage($page);
		
		// default research
		$dates = $this->getAdaptedService()->findDates(Constants::DEFAULT_SEARCH_DATES_LIMIT);
		
		// search date in string
		$searchDateInStr = $this->getSearchDate($dates);
		
		// Complete parameters list for the renderer view
		$parameters = $this->completeViewParameters($searchDateInStr, $page, $dates);
		
		return $this->render(ConstViews::VIEW_HOME, $parameters);
	}
	
	/**
	 * (non-PHPdoc)
	 * @see \Lmi\EventBundle\Controller\AbstractController::completeViewParameters()
	 */
	protected  function completeViewParameters(&$viewParameters, $searchDateInStr, $page, $eventId)
	{
		// will contain view parameters
		parent::completeViewParameters($viewParameters, $searchDateInStr, $page, $eventId);
		
		if(array_key_exists(ConstParamAttributs::ATTRIBUTE_LIST_ELEMENTS, $viewParameters)) {
			$viewParameters[$this::NB_EVENTS_STARTED] = $this->container->get(ConstServices::SERVICE_EVENT)
															            ->countStartedEvents($viewParameters[ConstParamAttributs::ATTRIBUTE_LIST_ELEMENTS]);
		}
	}
	
	/**
	 * (non-PHPdoc)
	 * @see \Lmi\EventBundle\Controller\AbstractController::findEntitiesBy()
	 */
	protected function findEntitiesBy($criteria)
	{
		$date = $criteria['date'];
		$page = $criteria['page'];
		
		return $this->getAdaptedService()->findFromDate($date, $page, $this->getNbMaxEntitiesByPage());
	}
	
	/**
	 * (non-PHPdoc)
	 * @see \Lmi\CoreBundle\Controller\AbstractController::getClass()
	 */
	protected function getManagedClass()
	{
		return ConstClasses::CLASS_EVENT;
	}
	
}
?>

SalsaEvent/src/Lmi/EventBundle/Resources/views/Event/comment.html.twig
{% set detail = detail|default(false) %}
{% set listing = listing|default(false) %}
{% set cv = cv|default(false) %}
{% set comment = bean|default(null) %}
{% set isNewEntity = isNewEntity|default(false) %}

{% if comment %}
	{% if listing %}
		<div class="col-avatar-avis">
			<img src="{{ asset('bundles/sdzblog/images/avatar.jpg') }}" alt="avatar" />
		</div>
		
		{% if is_granted('ROLE_ADMIN') %}
		<div class="col-auteur-avis-1">
		{% else %}
		<div class="col-auteur-avis-2">
		{% endif %}
			<p><span class="important">
				<b>
				{% if comment.auteur is not null %}
					{{ comment.auteur.pseudo }},
				{% else %}
					{{ 'message.anonymous'|trans }},
				{% endif %}
				</b></span> <span class="listing-texte-size signale">{{ 'date.time.format1'|trans({'%date%': comment.date|date('d/m/Y'), '%time%': comment.date|date('H:i:s')}) }}</span>
			</p>
			<p class="listing-texte-size">{{ comment.contenu }}</p>
		</div>
		{% if is_granted('ROLE_ADMIN') %}
			<div class="col-check-all"><input type="checkbox" name="myIds[]" value="{{ comment.id }}"/></div>
		{% endif %}
	{% else %}
		{% if is_granted('ROLE_ADMIN') %}
			<h2 class="header important">
				{% if comment.auteur is not null %}
					{{ 'comment.author'|trans({'%pseudo%': comment.auteur.pseudo }) }}
				{% else %}
					{{ 'comment.anonymous'|trans }}
				{% endif %}
			</h2><br />
			<p class="indent important">{{ 'date.time.format0'|trans({'%date%': comment.date|date('d/m/Y'), '%time%': comment.date|date('H:i:s')}) }}</p>
		{% endif %}
		<div class="indent">
			<div class="comment">
				<p class="notice">{{ 'comment.summary.label'|trans }}</p>
				<p class="well">{{ comment.contenu }}</p>
			</div>
		</div>
	{% endif %}
{% else %}
	<div class="sent-comment-ok">
		<p class="success">{{ 'comment.sent.ok'|trans }}</p>
		<p class="value">{{ 'comment.info'|trans }}</p>
	</div>
{% endif %}

SalsaEvent/src/Lmi/EventBundle/Resources/views/Event/ecole.html.twig
{% set listing = listing|default(false) %}
{% set detail = detail|default(false) %}
{% set ecole = bean|default(null) %}
{% set locale = bean|default('fr') %}

{% if ecole %}
	{% if listing %}
		{% include "LmiEventBundle:Event:listing_row_logo.html.twig" with {'logo': ecole.logo, 'default': 'bundles/sdzblog/images/logo_ecole.jpg', 'alt' : 'ecole.jpg'} %}
		{% include "LmiEventBundle:Event:listing_row_texte.html.twig" with {'detailUrl': 'lmievent_voir_ecole', 'entityId': ecole.id, 'title' : ecole.nom, 'texte' : ecole.descriptionTexte} %}
	{% elseif detail %}
		<h2 class="header">{{ ecole.nom }}</h2><br />
		<div class="indent">
			<p class="notice">{{ 'ecole.description.label'|trans }}</p>
			<p class="well">
				{{ ecole.descriptionTexte }}
			</p>
			{% if ecole.adresse is not null %}
				<p><span class="notice">{{ 'ecole.address.label'|trans }}:</span> {{ ecole.adresse.inStringFormat }}</p>
			{% endif %}
			
			{% if ecole.link %}<p class="notice">{{ 'ecole.link.label'|trans }} <a class="value" href="{{ ecole.link }}">{{ 'link.wiki' | trans }}</a></p>{% endif %}
			{% if ecole.tel %}<p class="notice">{{ 'ecole.phone.label'|trans }} <span class="value">{{ ecole.tel }}</span></p>{% endif %}
			{% if ecole.logo %}
				<p class="notice">{{ 'ecole.logo.label'|trans }}
					<img src="{{ asset(ecole.logo.webPath | imagine_filter('thumb_100x100')) }}" alt="{{ ecole.logo.alt }}" />
				</p>
			{% endif %}
		</div>
	{% else %}
		<a href="{{ path('lmievent_voir_ecole', {'id': ecole.id}) }}">{{ ecole.nom }}</a>
		{% if ecole.adresse is not null %}
			<span class="important">- {{ ecole.adresse.ville }} {{ ecole.adresse.codePostal }}</span>
		{% endif %}
	{% endif %}
{% endif %}

SalsaEvent/src/Lmi/EventBundle/Resources/views/Event/images_panel.html.twig
{% if bean.images is not null and bean.images is not empty %}
	<div class="photos">
		<p class="notice">{{ 'activity.photos.label'|trans }}</p>
		<ul class="work">
			{% for image in bean.images %}
				{% if image %}
					<li class="boxgrid captionfull">
					{% if loop.index % 2 == 0 %}
						<span class="small pop2" data-bpopup='<img src="{{ asset(image.webPath) }}" />'>
					{% else %}
						<span class="small pop1" data-bpopup='<img src="{{ asset(image.webPath) }}" />'>
					{% endif %}
						<img src="{{ asset(image.webPath | imagine_filter('thumb_150x120')) }}" alt="{{ image.alt }}" />
						<span class="image-title"><center>titre{#{ image.titre }#}</center></span></span>
					</li>
				{% endif %} 
			{% endfor %}
		</ul>
	</div>
{% endif %}

SalsaEvent/src/Lmi/EventBundle/Resources/views/Event/index.html.twig
{% include "LmiCoreBundle:Core:resultSearch.html.twig" %}

SalsaEvent/src/Lmi/EventBundle/Resources/views/Event/listing_admin_subtab.html.twig
{% set detailUrl = detailUrl|default('#') %}
{% set entityId = entityId|default(null) %}
{% set title = title|default(null) %}
{% set texte = texte|default(null) %}

<div {% if is_granted('ROLE_ADMIN') %} class="cell-short-desc" {% else %} class="cell-long-desc" {% endif %}>
	<p class="sous-titre">
		<a class="title-link" href="{{ path(detailUrl, {'id': entityId} ) }}">{{ title }}</a>
	</p>
	<p class="listing-texte-size">{{ texte |truncate(80) }} </p>
</div>

{% if is_granted('ROLE_ADMIN') %}
	<div class="cell-ckbx"><input type="checkbox" name="myIds[]" value="{{ entityId }}"/></div>
{% endif %}

SalsaEvent/src/Lmi/EventBundle/Resources/views/Event/modifier.html.twig
{% extends "SdzBlogBundle::layout.html.twig" %}
 
{% block title %}
  {{ title }} - {{ parent() }}
{% endblock %}
 
{% block lmievent_body %}
 
	<h2>{{ title }}</h2>
 
	{% include "LmiEventBundle:Event:formulaire.html.twig" %}
	
{% endblock %}

SalsaEvent/src/Lmi/EventBundle/Resources/views/Event/page-cp-acc-tabs.html.twig
{% set tabDates = tabDates|default(null) %}
{% set event = event|default(null) %}
{% set listeElements = listeElements|default(null) %}
{% set routeSearch = routeSearch|default(null) %}

{% if event is not null %}
	{% if type == 'carpooling' %}
		<p style="margin-bottom: 20px; text-align:center; font-size: 1.2em"><b>Coivoiturages pour </b><span class="important">{{ event.identification }}</span></p>
	{% else %}
		<p style="margin-bottom: 20px; text-align:center; font-size: 1.2em"><b>Hébergements/Locations/Colocations pour </b><span class="important">{{ event.identification }}</span></p>
	{% endif %}
{% endif %}

{% if tabDates is not null %}
	<ul class="rest nav nav-tabs nav-justified">
		{% for date in tabDates %}
			<li {% if date.date == tabToActive %} class="active" {% endif %}>
				{% if date.date == today %}
					{% if event %}
						<a href="{{ path(routeSearch, {'date': date.date, 'eventId': event.id} ) }}">{{ 'day.today' | trans }}</a>
					{% else %}
						<a href="{{ path(routeSearch, {'date': date.date} ) }}">{{ 'day.today' | trans }}</a>
					{% endif %}
				{% elseif date.date == tomorrow %}
					{% if event %}
						<a href="{{ path(routeSearch, {'date': date.date, 'eventId': event.id} ) }}">{{ 'day.tomorrow' | trans }}</a>
					{% else %}
						<a href="{{ path(routeSearch, {'date': date.date} ) }}">{{ 'day.tomorrow' | trans }}</a>
					{% endif %}
				{% else %}
					{% if event %}
						<a href="{{ path(routeSearch, {'date': date.date, 'eventId': event.id} ) }}">{{ date.date }}</a>
					{% else %}
						<a href="{{ path(routeSearch, {'date': date.date} ) }}">{{ date.date }}</a>
					{% endif %}
				{% endif %}
			</li>
		{% else %}
			<p>Acun évènement trouvé</p>
		{% endfor %}
	</ul>
{% endif %}
	

SalsaEvent/src/Lmi/EventBundle/Resources/views/Event/rowEvent.html.twig
{% set event = element|default(null) %}
{% set soiree = event|soiree(event, tabToActive) %}
{% set pSoiree = event|periode(event, 'soiree') %}
{% set pStage = event|periode(event, 'stage') %}

<div class="soiree ligne">
	<!-- ----- -->
	<!-- Flyer -->
	<!-- ----- -->
	<div class="colEvent0 flyer">
		<p><img src="{{ asset('bundles/lmievent/images/logo_ecole.jpg' | imagine_filter('thumb_100x100')) }}" alt="messi" /></p>
		
		<p class="organizer">
			{% if event.organisateurs is not empty %}
				{{ event.mainOrganizer }}
			{% endif %}
		</p>
	</div>
	<!-- ----- ------>
	<!-- Fin Flyer -->
	<!-- ----- ------>
	
	<!-- ---- ---->
	<!-- Resume -->
	<!-- ---- ---->
	<div class="colEvent1 resume">
		<div class="contenu">
			<!-- Event title -->
			<div>
				<p class="event-hour">{{ pSoiree.dateDebut|date('H\\hi') }}</p>
				<p class="identification">{{ event.identification }}</p>
				<p class="clean" />
			</div>
			
			<!-- Short description -->
			<p class="short-desc">
				{% if event.soirees is not empty %}
					{% if event.stages is empty %}
						Soiree <span class="important">{{ event.ambiances|join('/') }}</span> de <span class="important">{{ pSoiree.dateDebut|date('H\\hi') }} à {{ pSoiree.dateFin|date('H\\hi') }}</span> avec <b>Dj XXX</b> aux platines
					{% else %}
						Soirée <span class="important">{{ event.ambiances|join('/') }}</span> + <span class="important">{{ event.stages|length }} stages</span> (Kiz, Salsa ...).
					{% endif %}
				{% endif %}
			</p>
			<!-- End Short description -->
			
			<!-- Localisation -->
			<p class="localisation">Salle "Le Temple" - <span class="important" style="background-color: #FBF2EF">{#{ soiree.adresse.ville }#}Bordeaux / Aquitaine / France</span></p>
			<p class="clean"></p>
			
			<!-- Services (car poolings, accommodations, stages) -->
			<div class="services">
				
				<!--  table for car poolings and accommodations-->
				<table>
					<tr><!-- car poolings line -->
						<td><b>covoiturages:</b></td>
						<td><span class="important">{{ event.availableCarpoolings|length }}</span> proposé(s)</td>
						<td><a href="#">Proposez</a></td>
						<td>
							{% if event.carpoolings is not empty %}
								<a href="{{ path('lmievent_rechercher_covoiturages', {'eventId': event.id} ) }}">Consultez</a>
							{% endif %}
						</td>
					</tr>
					<tr><!-- accommodations line -->
						<td><b>Hébergements:</b></td>
						<td><span class="important">{{ event.hebergements|length }}</span> proposé(s)</td>
						<td><a href="#">Proposez</a></td>
						<td>
							{% if event.hebergements is not empty %}
								<a href="{{ path('lmievent_rechercher_hebergements', {'eventId': event.id} ) }}">Consultez</a>
							{% endif %}
						</td>
					</tr>
				</table>
				<!-- End table for car poolings and accommodations-->
				
				<!--  stages block -->
				<div class="stages">
					<label>Stages:</label>
					<p>
					{% for stage in event.stages %}
						{% if loop.index is divisibleby(2) %}
							<a href=""><span style="color: black">{{ stage.danse }}</span></a>
						{% else %}
							<a href="">{{ stage.danse }}</a>
						{% endif %}
					{% endfor %}
					</p>
				</div>
				<!-- End stages block -->
			</div>
			<!-- End Services (car poolings, accommodations, stages) -->
		</div>
		
		<div class="programme">
			<p style="font-weight: bold;color: blue"><u>Programe :</u></p>
			<p style="font-size:85%"><span style="font-weight: bold">{{ pStage.dateDebut|date('H\\hi') }} - {{ pStage.dateFin|date('H\\hi') }}:</span> Stages</p>
			<p style="font-size:85%"><span style="font-weight: bold">{{ pSoiree.dateDebut|date('H\\hi') }} - {{ pSoiree.dateFin|date('H\\hi') }}:</span> Soirée</p>
		</div>
		
{# 		<p class="clean"></p>#}
	</div>
	<!-- ---- -------->
	<!-- Fin Resume -->
	<!-- ---- -------->
	
	<div class="clean"></div>
</div>

SalsaEvent/src/Lmi/EventBundle/Resources/views/Event/searchForm.html.twig
{# {% set redirectUrl = redirectUrl|default(null) %}#}
{# {% set page = page|default(null) %}#}

<div class="form">
	<form method="post" {{ form_enctype(searchForm) }}>
		{{ form_widget(searchForm) }}
	</form>
</div>